### ISSUE TITLE
Add blobs to dropdown?

### ISSUE THREAD

**Issue by JTD420** [graemephi/imgur-uploader#4]
Hi,

This tool is EXACTLY what I've been looking for so thank you for the great work on it so far!

I just had a quick question regarding how difficult it'd be to implement blob type support?

More and more sites are beginning to use blobs to distribute image/big file size content to their users... These blobs are loaded on the clients side so the URLs do not actually contain images but rather an encoded string so it's not immediately detected as an image by browsers like chrome...

You can still right click and save as .jpeg but the option to rehost to imgur doesn't show as blobs aren't detected as images.

Hope you can add this functionality as I believe that would truly perfect this extension in every way!

Thanks again,
JTD

**Comment by graemephi** [comment]
It should! For example, you can upload straight from google image search, and all those images are embedded as data urls.

Like this:
```
<img id="C9aWBgKmfp_g6M:" src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBw0NDQ0NDQ0PDQ0NDQ0NDQ0NDxANDQ0NFREWFhURFRUYHSggGBoxGxUVITEhJSk3Ljo6Fx8/OD84NygtOisBCgoKBQUFDgUFDisZExkrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrK//AABEIAOEA4QMBIgACEQEDEQH/xAAWAAEBAQAAAAAAAAAAAAAAAAAAAQf/xAAWEAEBAQAAAAAAAAAAAAAAAAAAARH/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A3EQBRAFEAUQBRAFEAUQBRAFEAUQBRAFEAUQBRAFEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABRAAAAAAAAAAAAAAAAAAAAAAAAAAAAABUUEAAAAAAAAAAAAAAAAAAAAAAAAAAAABQQAAAAAAAAAAAAAAAAAAAAAAAAAAADQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUAQAFQAFoAgAFAAgACgCAAAAFUBAAUAH/9k=" jsaction="load:str.tbn" class="rg_ic rg_i" alt="Image result for transparent 1x1 pixel" style="width: 193px; height: 193px; margin-left: 0px; margin-right: 0px; margin-top: 0px;" data-atf="1">
```

This works. 

Buut I think this just might be out of our hands. If Chrome displays `Save image as` but not this extension's `Rehost image` then that's Chromes fault, because all we do is register a context menu item for the `image` context. But if Chrome displays something other than `Save image as` then `Rehost image` won't appear. I don't think there's anything we can do about that.

**Comment by JTD420** [comment]
Hi sorry I don't think I explained the issue particularly well!

Let me try show you an example. I've used Bill Gates as an example picture for this.. This website does facial recognition on images you provide. 
https://pimeyes.com/en/search/all/0d3e42901aaedc817322f3ea998dfb5dab97c8204281/global/all

Right clicking on any of the displayed images doesn't show the context menu because the actual embed is done without an image extension or mime type etc. Such like this;
`<img _ngcontent-atf-c10="" src="blob:https://pimeyes.com/26a417a6-f41d-467d-a54e-fb61fbc0b4b2" title="https://pimeyes.com" class="ng-star-inserted">`

Browsing direct to the blob link will display the image directly and then right clicking will show the normal context menu options such as save image as and open in new tab however the upload to imgur context still doesn't appear.

Hopefully that gives you enough information to investigate it!

Regards
JTD :)

**Comment by graemephi** [comment]
Ah, the issue there isn't the way the image is embedded but that there is a clickable div element covering the image. If you remove it (`<div ... class='zoom'>`) the context menu triggers correctly and the blob is rehostable from the page. For something like this I don't think there's anything I can do.

Thanks for the example though, sometimes these things can be simple to fix or work around on my end so I don't mind having a look.
