### ISSUE TITLE
Extension has been removed frome Chrome Web Store

### ISSUE THREAD

**Issue by Rosenstein** [graemephi/imgur-uploader#5]
![image](https://user-images.githubusercontent.com/4959837/115475141-4b021880-a23f-11eb-8c56-0de75c9f83fa.png)

**Comment by graemephi** [comment]
Yeah, you need a privacy policy now, even if you don't collect any user information. The message they sent out about this said you'd get a warning before they'd take anything down and I did not get a warning :( I threw one up on the [wiki](https://github.com/graemephi/imgur-uploader/wiki), if it passes muster I'll close this issue.

**Comment by graemephi** [comment]
And we're good now. Thanks for opening the issue.
