### ISSUE TITLE
Suggestion: post image to reddit

### ISSUE THREAD

**Issue by notNSANE** [graemephi/imgur-uploader#7]
This is a niche usage so ideally should be optional. There's an extension that already does this but I think it would be great if this one could do it too, if possible. Here it is: https://chrome.google.com/webstore/detail/reddit-image-uploader/pnenllbmjkcicocfhcbjifaadeikmmmm

I think the option should appear below "rehost image" when you right click on an image.

**Comment by graemephi** [comment]
The maintenance burden of this extension is very low and I like to keep tight control of the scope of any extensions I put up (the chrome webstore wants this, too). I'm not gonna expand either without a really good reason.
